[tool.poetry]
name = "tcp_over_ping"
version = "0.1.0"
description = ""
authors = ["Nir Geller <gnir.work@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]
pytest = "^3.0"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
